<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-04T18:51:08 CDT" name="Suite" finished-at="2025-05-04T18:51:29 CDT" duration-ms="20163">
    <groups>
    </groups>
    <test started-at="2025-05-04T18:51:08 CDT" name="Error Validation In Login" finished-at="2025-05-04T18:51:15 CDT" duration-ms="6243">
      <class name="SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApllicaton()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest@57a3e26a]" started-at="2025-05-04T18:51:09 CDT" name="launchApllicaton" finished-at="2025-05-04T18:51:14 CDT" duration-ms="5264" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApllicaton -->
        <test-method signature="LoginErrorValidatde()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest@57a3e26a]" started-at="2025-05-04T18:51:14 CDT" name="LoginErrorValidatde" finished-at="2025-05-04T18:51:14 CDT" duration-ms="663" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Incorrect email or password. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Incorrect email or password. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at Souradipta.AbstractClass.AbstractClass.ValidateErrorMessage(AbstractClass.java:56)
at Souradipta.PageObjectModel.LandingPage.LoginErrorValidation(LandingPage.java:51)
at SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest.LoginErrorValidatde(ErrorValidationTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidatde -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest@57a3e26a]" started-at="2025-05-04T18:51:15 CDT" name="DriverClose" finished-at="2025-05-04T18:51:15 CDT" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
      </class> <!-- SouradiptaMaity.TestNgLearn.tests.ErrorValidationTest -->
    </test> <!-- Error Validation In Login -->
    <test started-at="2025-05-04T18:51:08 CDT" name="Product Order Validation" finished-at="2025-05-04T18:51:29 CDT" duration-ms="20163">
      <class name="SouradiptaMaity.TestNgLearn.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApllicaton()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.SubmitOrderTest@503f91c3]" started-at="2025-05-04T18:51:09 CDT" name="launchApllicaton" finished-at="2025-05-04T18:51:14 CDT" duration-ms="5279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApllicaton -->
        <test-method signature="SubmitOrder()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.SubmitOrderTest@503f91c3]" started-at="2025-05-04T18:51:14 CDT" name="SubmitOrder" finished-at="2025-05-04T18:51:28 CDT" duration-ms="14622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="DriverClose()[pri:0, instance:SouradiptaMaity.TestNgLearn.tests.SubmitOrderTest@503f91c3]" started-at="2025-05-04T18:51:28 CDT" name="DriverClose" finished-at="2025-05-04T18:51:29 CDT" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DriverClose -->
      </class> <!-- SouradiptaMaity.TestNgLearn.tests.SubmitOrderTest -->
    </test> <!-- Product Order Validation -->
  </suite> <!-- Suite -->
</testng-results>
